services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    command: php -S 0.0.0.0:8000 -t public
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "mysql://symfony:symfony@db:3306/symfony"

  db:
    image: mariadb:10.6
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

